# Generated by Django 4.2.7 on 2024-01-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250)),
                ('DOB', models.DateField()),
                ('age', models.TextField()),
                ('gender', models.TextField()),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
